### ISSUE TITLE
افزودن پیام‌رسان گپ به لیست استارتاپ‌های ساخت مشهد

### ISSUE THREAD

**Issue by pordel** [Hameds/softwaretalks#11]
با سلام 
لطفا پیام رسان ملی گپ که توسط شرکت توسعه سامان ساخته شده است را نیز به لیست اضافه بفرمایید 
http://gap.im

تشکر

**Comment by Hameds** [comment]
<div dir="rtl">
نام موسس رو هم می‌فرمایید؟ یا از عنوان شرکت استفاده کنیم؟
</div>
